name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install dependencies
      run: make
      
    - name: Copy secrets
      uses: nowactions/envsubst@v1.0.1
      with:
        input: ./.screepsasNoCreds.yaml
        output: ./.screepsas.yaml
      env:
        MMO_TOKEN: ${{ secrets.MMO_TOKEN }}
    
    - name: Trigger spawn
      run: screepsautospawner respawn
